"""add indexes relationships cascade timezone

Revision ID: 0c487a38615c
Revises: 
Create Date: 2026-07-17 00:14:57.711544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c487a38615c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_incidents_asset_id'), 'incidents', ['asset_id'], unique=False)
    op.alter_column('node_confidence', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_node_confidence_asset_id'), 'node_confidence', ['asset_id'], unique=False)
    op.alter_column('sensor_readings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_readings_asset_sensor_time', 'sensor_readings', ['asset_id', 'sensor_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_asset_id'), 'sensor_readings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_type'), 'sensor_readings', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_topology_edges_from_asset_id'), 'topology_edges', ['from_asset_id'], unique=False)
    op.create_index(op.f('ix_topology_edges_to_asset_id'), 'topology_edges', ['to_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_edges_to_asset_id'), table_name='topology_edges')
    op.drop_index(op.f('ix_topology_edges_from_asset_id'), table_name='topology_edges')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_type'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_asset_id'), table_name='sensor_readings')
    op.drop_index('ix_readings_asset_sensor_time', table_name='sensor_readings')
    op.alter_column('sensor_readings', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_node_confidence_asset_id'), table_name='node_confidence')
    op.alter_column('node_confidence', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_incidents_asset_id'), table_name='incidents')
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
